### ISSUE TITLE
Record duplication

### ISSUE THREAD

**Issue by trrbl** [rs-pro/rails_admin_settings#3]
When i creating new group in settings.yml, i got duplication records from "new group" to "main".
For example:

```
system:
  importing_row:
    type: integer
    value: 0
  import_last_row:
    type: integer
    value: 0
  import_errors:
    type: string
    value: ''
```

![00007](https://cloud.githubusercontent.com/assets/4060934/3144515/50635072-ea23-11e3-94cb-8f42940cbfc7.png)
